const canvas=document.getElementById("board"),ctx=canvas.getContext("2d"),statusEl=document.getElementById("status"),turnEl=document.getElementById("turn"),diceEl=document.getElementById("dice"),rollBtn=document.getElementById("roll"),modeEl=document.getElementById("mode"),scoresEl=document.getElementById("scores"),voiceBtn=document.getElementById("voiceToggle");
const C=["#e53935","#20a55a","#f4c430","#2878e8"],names=["লাল","সবুজ","হলুদ","নীল"],starts=[0,13,26,39],path=[];for(let i=0;i<52;i++){let a=i/52*Math.PI*2-Math.PI/2;path.push({x:360+255*Math.cos(a),y:360+255*Math.sin(a)})}
const homePos=[[95,95],[625,95],[625,625],[95,625]],safe=[0,8,13,21,26,34,39,47],S={players:4,turn:0,dice:0,rolled:false,voice:true,winner:null,tokens:[]};
const L={start:["চল ভাই, লুডু খেলি—দেহি আজ কার কপাল খোলে!","খেলা শুরু অইছে, সবাই রেডি অও!","আইজকা কিন্তু হারলে অজুহাত চলতো নায়!"],move:["গুটি আগাইতেছে!","এইবার জায়গাডা দখল কর!","ওই গুটি, থামিস না!"],capture:["আহা! গুটি খাইয়া দিল!","ওইরে! গুটি কাইটা ঘরে পাঠাইছে!","বাপরে বাপ! কী চাল দিছে!"],six:["ওই! ছয়! আবার চাল তুমার!","ভাগ্য তো আজ তুমার লগেই আছে!","ছয় পাইছো, আরেকবার দে!"],win:["ইয়াহ! জিতছি! আজকের লুডু চ্যাম্পিয়ন আমি!","ওই হইছে! সব গুটি ঘরে!","কইছিলাম না, আইজকা আমিই জিতমু!"]};
function rnd(a){return a[Math.floor(Math.random()*a.length)]}function say(t){statusEl.textContent=t;if(!S.voice||!window.speechSynthesis)return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang="bn-BD";u.rate=.95;speechSynthesis.speak(u)}
function init(){S.players=modeEl.value==="4p"?4:2;S.turn=0;S.dice=0;S.rolled=false;S.winner=null;S.tokens=Array.from({length:S.players},()=>Array(4).fill(-1));say(rnd(L.start));render()}
function gpos(p,v){return v<0||v>=52?-1:(starts[p]+v)%52}function moves(p,d){return S.tokens[p].map(v=>v===57?false:v===-1?d===6:v+d<=57)}
function roll(){if(S.winner!==null||S.rolled||(S.players===2&&S.turn===1))return;S.dice=1+Math.floor(Math.random()*6);S.rolled=true;diceEl.textContent=["⚀","⚁","⚂","⚃","⚄","⚅"][S.dice-1];say(S.dice===6?rnd(L.six):["এক্কা আইছে!","দুই অইছে!","তিন আইছে!","চার অইছে!","পাঁচ আইছে!","ওই মিয়া! ছয় আইছে!"][S.dice-1]);render();if(!moves(S.turn,S.dice).some(Boolean))setTimeout(next,650)}
function move(i){if(!S.rolled||!moves(S.turn,S.dice)[i]||S.winner!==null)return;let p=S.turn,d=S.dice,v=S.tokens[p][i];S.tokens[p][i]=v===-1?0:v+d;let pos=gpos(p,S.tokens[p][i]),cap=false;if(pos>=0&&pos<52&&!safe.includes(pos)){for(let q=0;q<S.players;q++)if(q!==p)for(let j=0;j<4;j++){let ov=S.tokens[q][j];if(ov>=0&&ov<52&&gpos(q,ov)===pos){S.tokens[q][j]=-1;cap=true}}}say(cap?rnd(L.capture):S.tokens[p][i]===57?rnd(L.win):rnd(L.move));if(S.tokens[p].every(v=>v===57)){S.winner=p;say(p===0?rnd(L.win):names[p]+" জিতছে!");}else if(d!==6)next();else{S.rolled=false;diceEl.textContent="🎲"}render()}
function next(){S.rolled=false;diceEl.textContent="🎲";S.turn=(S.turn+1)%S.players;render();if(S.players===2&&S.turn===1)setTimeout(cpu,650)}
function cpu(){if(S.winner!==null)return;S.dice=1+Math.floor(Math.random()*6);S.rolled=true;diceEl.textContent=["⚀","⚁","⚂","⚃","⚄","⚅"][S.dice-1];say("হুনো, এবার কম্পিউটারের চাল!");render();let i=moves(1,S.dice).findIndex(Boolean);if(i<0){setTimeout(next,600);return}setTimeout(()=>move(i),650)}
function xy(p,v,i){if(v<0){let h=homePos[p];return{x:h[0]+(i%2?19:-19),y:h[1]+(i>1?19:-19)}}if(v===57)return{x:360,y:360};let q=path[gpos(p,v)];return{x:q.x+(i%2?7:-7),y:q.y+(i>1?7:-7)}}
function draw(){ctx.clearRect(0,0,720,720);ctx.fillStyle="#f3e7cc";ctx.fillRect(0,0,720,720);ctx.strokeStyle="#0b5b43";ctx.lineWidth=8;ctx.strokeRect(8,8,704,704);for(let p=0;p<4;p++){ctx.fillStyle=C[p]+"30";ctx.fillRect(p%2?370:20,p<2?20:370,330,330)}for(let i=0;i<52;i++){let q=path[i];ctx.beginPath();ctx.arc(q.x,q.y,18,0,7);ctx.fillStyle=safe.includes(i)?"#ffe58a":"#fff";ctx.fill();ctx.strokeStyle="#777";ctx.stroke();if(safe.includes(i)){ctx.font="14px sans-serif";ctx.fillText("⭐",q.x-8,q.y+5)}}ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(360,360,78,0,7);ctx.fill();ctx.stroke();ctx.fillStyle="#123";ctx.textAlign="center";ctx.font="bold 22px sans-serif";ctx.fillText("SYLHET",360,355);ctx.font="16px sans-serif";ctx.fillText("LUDO",360,378);for(let p=0;p<S.players;p++)for(let i=0;i<4;i++){let q=xy(p,S.tokens[p][i],i);ctx.beginPath();ctx.arc(q.x,q.y,15,0,7);ctx.fillStyle=C[p];ctx.fill();ctx.lineWidth=3;ctx.strokeStyle="#fff";ctx.stroke();ctx.fillStyle="#fff";ctx.font="bold 11px sans-serif";ctx.fillText(i+1,q.x,q.y+4)}}
function render(){draw();turnEl.textContent=S.winner!==null?"🏆 "+names[S.winner]+" Winner!":(S.turn===0?"🔴 ":"🟢 ")+names[S.turn]+" Player-এর পালা";scoresEl.innerHTML=Array.from({length:S.players},(_,p)=>'<div class="score"><span>'+names[p]+'</span><b>'+S.tokens[p].filter(v=>v===57).length+'/4 🏠</b></div>').join("");rollBtn.disabled=S.winner!==null||S.rolled||(S.players===2&&S.turn===1)}
canvas.addEventListener("click",e=>{let r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*720/r.width,y=(e.clientY-r.top)*720/r.height;for(let i=0;i<4;i++){let q=xy(S.turn,S.tokens[S.turn][i],i);if(Math.hypot(x-q.x,y-q.y)<26){move(i);break}}});rollBtn.onclick=roll;document.getElementById("newGame").onclick=init;modeEl.onchange=init;voiceBtn.onclick=()=>{S.voice=!S.voice;voiceBtn.textContent=S.voice?"🔊 Voice ON":"🔇 Voice OFF"};init();